spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel4.cloudtype.app:31526/web
    username: root
    password: 3985
    thymeleaf:
      cache: false

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create